version: '3'
services:
  app:
    environment:
      RAILS_ENV: development
    build:
      context: ../
      dockerfile: ./localServer/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - db:/app/db
    ports:
      - "3000:3000"
      
volumes:
  db:
    driver: local