version: '3'
services:
  app:
    image: app
    environment:
      RAILS_ENV: development
      BASIC_AUTH_USER: user
      BASIC_AUTH_PASS: pass
    build:
      context: ../
      dockerfile: ./localServer/Dockerfile
    command: >
      sh -c "bundle install &&
             bundle exec rails db:migrate && 
             tail -f /dev/null"
    volumes:
      - ../app:/app
      - db:/app/db
    ports:
      - "3000:3000"
      
volumes:
  db:
    driver: local